# Generated by Django 5.2.8 on 2025-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='image',
        ),
        migrations.AddField(
            model_name='thing',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
