# Generated by Django 5.2.8 on 2025-11-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_thing_image_thing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
