# Generated by Django 5.2.8 on 2025-12-29 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_cartitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('thing', 'user')},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
